AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  CoffeeShopFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/CoffeeShop/
      Handler: CoffeeShop::CoffeeShop.Function::FunctionHandler
      Runtime: dotnetcore3.1
    FunctionName: Testing-Lambda-CoffeeShop
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CoffeeShopFunction:
    Description: "CoffeeShop Lambda Function"
    Value: !Ref CoffeeShopFunction
    Export:
      Name: !Sub Testing-Lambda-CoffeeShop
  CoffeeShopFunctionIamRole:
    Description: "Implicit IAM Role created for CoffeeShop function"
    Value: !GetAtt CoffeeShopFunctionRole.Arn
    Export:
      Name: !Sub Testing-Lambda-CoffeShop-Arn
